#############################################################################
# Makefile for building: group3
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon May 4 12:47:10 2015
# Project:  group3.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile group3.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iincludes -I../../opencv2410/src/include -I/usr/local/cuda-7.0/targets/x86_64-linux/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -L/home/cyxia/opencv2410/buildGPU/lib -lopencv_core -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lcudart -lcuda -lcublas -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Qts/main.cpp \
		src/Qts/mainwindow.cpp \
		src/Qts/streamthread.cpp \
		src/Qts/viewqt.cpp \
		src/Qts/modelsqt.cpp \
		src/trackers/utils.cpp \
		src/trackers/buffers.cpp moc_mainwindow.cpp \
		moc_streamthread.cpp \
		moc_viewqt.cpp
OBJECTS       = ${OBJECTS_DIR}klttracker_cuda.o \
		main.o \
		mainwindow.o \
		streamthread.o \
		viewqt.o \
		modelsqt.o \
		utils.o \
		buffers.o \
		moc_mainwindow.o \
		moc_streamthread.o \
		moc_viewqt.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		group3.pro
QMAKE_TARGET  = group3
DESTDIR       = 
TARGET        = group3

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: group3.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile group3.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile group3.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/group31.0.0 || $(MKDIR) .tmp/group31.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/group31.0.0/ && $(COPY_FILE) --parents src/trackers/klttracker.cu .tmp/group31.0.0/ && $(COPY_FILE) --parents includes/Qts/mainwindow.h includes/Qts/streamthread.h includes/Qts/viewqt.h includes/Qts/modelsqt.h includes/trackers/utils.h includes/trackers/buffers.h includes/trackers/tracker.h includes/trackers/klttracker.h .tmp/group31.0.0/ && $(COPY_FILE) --parents src/Qts/main.cpp src/Qts/mainwindow.cpp src/Qts/streamthread.cpp src/Qts/viewqt.cpp src/Qts/modelsqt.cpp src/trackers/utils.cpp src/trackers/buffers.cpp .tmp/group31.0.0/ && (cd `dirname .tmp/group31.0.0` && $(TAR) group31.0.0.tar group31.0.0 && $(COMPRESS) group31.0.0.tar) && $(MOVE) `dirname .tmp/group31.0.0`/group31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/group31.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_cuda_make_all: ${OBJECTS_DIR}klttracker_cuda.o
compiler_cuda_clean:
	-$(DEL_FILE) ${OBJECTS_DIR}klttracker_cuda.o
${OBJECTS_DIR}klttracker_cuda.o: ../../opencv2410/src/include/opencv2/opencv.hpp \
		src/trackers/klttracker.cu \
		src/trackers/klttracker.cu \
		/usr/include/stdc-predef.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_config.h \
		/usr/include/features.h \
		/usr/include/x86_64-linux-gnu/sys/cdefs.h \
		/usr/include/x86_64-linux-gnu/bits/wordsize.h \
		/usr/include/x86_64-linux-gnu/gnu/stubs.h \
		/usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/limits.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/syslimits.h \
		/usr/include/limits.h \
		/usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
		/usr/include/x86_64-linux-gnu/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
		/usr/include/x86_64-linux-gnu/bits/xopen_lim.h \
		/usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/common_functions.h \
		/usr/include/string.h \
		/usr/include/xlocale.h \
		/usr/include/x86_64-linux-gnu/bits/string3.h \
		/usr/include/time.h \
		/usr/include/x86_64-linux-gnu/bits/time.h \
		/usr/include/x86_64-linux-gnu/bits/types.h \
		/usr/include/x86_64-linux-gnu/bits/typesizes.h \
		/usr/include/x86_64-linux-gnu/bits/timex.h \
		/usr/include/c++/4.8/new \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/c++config.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/os_defines.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/cpu_defines.h \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdarg.h \
		/usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
		/usr/include/x86_64-linux-gnu/bits/stdio.h \
		/usr/include/x86_64-linux-gnu/bits/stdio2.h \
		/usr/include/stdlib.h \
		/usr/include/x86_64-linux-gnu/bits/waitflags.h \
		/usr/include/x86_64-linux-gnu/bits/waitstatus.h \
		/usr/include/endian.h \
		/usr/include/x86_64-linux-gnu/bits/endian.h \
		/usr/include/x86_64-linux-gnu/bits/byteswap.h \
		/usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
		/usr/include/x86_64-linux-gnu/sys/types.h \
		/usr/include/x86_64-linux-gnu/sys/select.h \
		/usr/include/x86_64-linux-gnu/bits/select.h \
		/usr/include/x86_64-linux-gnu/bits/sigset.h \
		/usr/include/x86_64-linux-gnu/bits/select2.h \
		/usr/include/x86_64-linux-gnu/sys/sysmacros.h \
		/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h \
		/usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
		/usr/include/x86_64-linux-gnu/bits/stdlib.h \
		/usr/include/assert.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions.h \
		/usr/include/math.h \
		/usr/include/x86_64-linux-gnu/bits/huge_val.h \
		/usr/include/x86_64-linux-gnu/bits/huge_valf.h \
		/usr/include/x86_64-linux-gnu/bits/huge_vall.h \
		/usr/include/x86_64-linux-gnu/bits/inf.h \
		/usr/include/x86_64-linux-gnu/bits/nan.h \
		/usr/include/x86_64-linux-gnu/bits/mathdef.h \
		/usr/include/x86_64-linux-gnu/bits/mathcalls.h \
		/usr/include/x86_64-linux-gnu/bits/mathinline.h \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_launch_parameters.h \
		includes/trackers/klttracker.h \
		includes/trackers/tracker.h \
		includes/trackers/utils.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/c++allocator.h \
		/usr/include/c++/4.8/ext/new_allocator.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		includes/trackers/buffers.h \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/x86_64-linux-gnu/bits/wchar.h \
		/usr/include/x86_64-linux-gnu/bits/wchar2.h \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/c++locale.h \
		/usr/include/c++/4.8/clocale \
		/usr/include/locale.h \
		/usr/include/x86_64-linux-gnu/bits/locale.h \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/cctype \
		/usr/include/ctype.h \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/gthr.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/gthr-default.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/x86_64-linux-gnu/bits/sched.h \
		/usr/include/x86_64-linux-gnu/bits/setjmp.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/atomic_word.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/wctype.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/ctype_base.h \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/ctype_inline.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/basic_file.h \
		/usr/include/x86_64-linux-gnu/c++/4.8/bits/c++io.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		../../opencv2410/src/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include/float.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h \
		/usr/include/stdint.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include/emmintrin.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include/xmmintrin.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include/mmintrin.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include/mm_malloc.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/cstddef \
		/usr/include/c++/4.8/complex \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/map \
		/usr/include/c++/4.8/bits/stl_tree.h \
		/usr/include/c++/4.8/bits/stl_map.h \
		/usr/include/c++/4.8/bits/stl_multimap.h \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/include/c++/4.8/limits \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/photo/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/include/c++/4.8/list \
		/usr/include/c++/4.8/bits/stl_list.h \
		/usr/include/c++/4.8/bits/list.tcc \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/include/c++/4.8/iostream \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/include/c++/4.8/valarray \
		/usr/include/c++/4.8/bits/valarray_array.h \
		/usr/include/c++/4.8/bits/valarray_array.tcc \
		/usr/include/c++/4.8/bits/valarray_before.h \
		/usr/include/c++/4.8/bits/slice_array.h \
		/usr/include/c++/4.8/bits/valarray_after.h \
		/usr/include/c++/4.8/bits/gslice.h \
		/usr/include/c++/4.8/bits/gslice_array.h \
		/usr/include/c++/4.8/bits/mask_array.h \
		/usr/include/c++/4.8/bits/indirect_array.h \
		/usr/local/include/opencv2/contrib/openfabmap.hpp \
		/usr/include/c++/4.8/set \
		/usr/include/c++/4.8/bits/stl_set.h \
		/usr/include/c++/4.8/bits/stl_multiset.h \
		/usr/local/include/opencv2/gpu/gpu.hpp \
		/usr/include/c++/4.8/memory \
		/usr/include/c++/4.8/bits/stl_raw_storage_iter.h \
		/usr/include/c++/4.8/backward/auto_ptr.h \
		/usr/local/include/opencv2/core/gpumat.hpp \
		/usr/local/include/opencv2/core/cuda_devptrs.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cublas.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cublas_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuComplex.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_config.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/common_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_constants.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions_decls.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_launch_parameters.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/syslimits.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_constants.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions_decls.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_constants.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions_decls.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_constants.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions_decls.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_35_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_double_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_20_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_30_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/sm_32_intrinsics.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_fetch_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/channel_descriptor.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuda_device_runtime_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_indirect_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_functions.hpp \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint-gcc.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cublas_api.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuComplex.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/cuComplex.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/host_defines.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda-7.0/targets/x86_64-linux/include/texture_types.h
	/usr/local/cuda/bin/nvcc -m64 -O3 -arch=sm_30 -c --compiler-options -fno-strict-aliasing -use_fast_math --ptxas-options=-v -I/home/cyxia/GitHub/group3/includes -I/home/cyxia/opencv2410/src/include -I/usr/local/cuda/include -L/home/cyxia/opencv2410/buildGPU/lib -lopencv_core -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lcudart -lcuda -lcublas src/trackers/klttracker.cu -o ${OBJECTS_DIR}klttracker_cuda.o 2>&1 | sed -r "s/\(([0-9]+)\)/:\1/g" 1>&2

compiler_moc_header_make_all: moc_mainwindow.cpp moc_streamthread.cpp moc_viewqt.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_streamthread.cpp moc_viewqt.cpp
moc_mainwindow.cpp: includes/Qts/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) includes/Qts/mainwindow.h -o moc_mainwindow.cpp

moc_streamthread.cpp: includes/Qts/streamthread.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) includes/Qts/streamthread.h -o moc_streamthread.cpp

moc_viewqt.cpp: includes/Qts/viewqt.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) includes/Qts/viewqt.h -o moc_viewqt.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_cuda_clean compiler_moc_header_clean 

####### Compile

main.o: src/Qts/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/Qts/main.cpp

mainwindow.o: src/Qts/mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/Qts/mainwindow.cpp

streamthread.o: src/Qts/streamthread.cpp ../../opencv2410/src/include/opencv2/opencv.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o streamthread.o src/Qts/streamthread.cpp

viewqt.o: src/Qts/viewqt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewqt.o src/Qts/viewqt.cpp

modelsqt.o: src/Qts/modelsqt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelsqt.o src/Qts/modelsqt.cpp

utils.o: src/trackers/utils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o src/trackers/utils.cpp

buffers.o: src/trackers/buffers.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buffers.o src/trackers/buffers.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_streamthread.o: moc_streamthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_streamthread.o moc_streamthread.cpp

moc_viewqt.o: moc_viewqt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewqt.o moc_viewqt.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/cyxia/GitHub/group3/build/ || $(MKDIR) $(INSTALL_ROOT)/home/cyxia/GitHub/group3/build/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/cyxia/GitHub/group3/build/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/home/cyxia/GitHub/group3/build/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/cyxia/GitHub/group3/build/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/cyxia/GitHub/group3/build/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

